[package]
name = "lastify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = "0.12.0"
lastfm = "0.8.1"
dotenv = "0.15.0"
